// Stories 6-10: Music School, Little Scientist, Junior Chef, Young Gardener, Star Coder
const stories6to10 = [

    {
        id: "music-school", file: "musicSchool", title: "{{CHILD}}'s Music School", emoji: "🎵",
        theme: "Skill Stories", lesson: "Patience", coverColor: "#FF9F43",
        description: "Discover the joy of music with {{CHILD}} and learn that beautiful things take patience!",
        pages: [
            ["The music room was filled with instruments of every kind.", "Guitars hung on the walls, drums sat in corners, and a piano gleamed.", "{{CHILD}}'s eyes went wide — so many sounds waiting to happen!"],
            ["\"Which instrument calls to you?\" asked the music teacher, Mr. Ray.", "{{CHILD}} walked slowly past each one, listening with their heart.", "Their hand reached out and touched the smooth keys of the piano."],
            ["\"Wonderful choice!\" Mr. Ray pulled out the bench.", "{{CHILD}} sat down and pressed one key. A clear note rang out.", "\"That's middle C — the center of the musical universe.\""],
            ["Both hands went on the keys and {{CHILD}} pressed everything at once.", "CLANG! A messy jumble of sounds filled the room.", "Mr. Ray laughed gently. \"Music is one note at a time.\""],
            ["\"Let's start with just three notes: C, D, and E,\" he showed.", "{{CHILD}} pressed each one slowly. Do, Re, Mi.", "The three notes sounded like a tiny staircase going up."],
            ["\"Now try going back down: E, D, C.\" Mi, Re, Do.", "Up and down, up and down — a simple musical ladder.", "\"My fingers want to go faster!\" {{CHILD}} said impatiently."],
            ["\"Patience,\" Mr. Ray said kindly. \"Speed follows steadiness.\"", "{{CHILD}} took a breath and played the notes slowly again.", "This time, each note was cleaner, rounder, more musical."],
            ["A simple song was introduced: \"Twinkle, Twinkle, Little Star.\"", "Just seven different notes, but the timing had to be right.", "{{CHILD}} played too fast and the song sounded rushed."],
            ["\"Think of each note as a word in a sentence,\" Mr. Ray explained.", "\"You wouldn't smoosh all your words together when talking.\"", "{{CHILD}} giggled and tried again, giving each note its own space."],
            ["By the end of the first lesson, the song was almost recognizable.", "\"You learned that in ONE lesson,\" Mr. Ray said, impressed.", "{{CHILD}} glowed. The piano felt like a new friend."],
            ["The next lesson introduced the left hand — bass notes.", "{{CHILD}}'s left hand felt clumsy and confused.", "\"It's like teaching your other hand to write,\" Mr. Ray sympathized."],
            ["Practice at home meant sitting at an old keyboard after dinner.", "ten minutes a day, {{MOTHER}} encouraged, and no more.", "\"Even professional musicians started with ten minutes.\""],
            ["Some days the notes came easily. Other days, nothing worked.", "{{CHILD}}'s fingers tripped over each other stubbornly.", "\"I'll never get this left hand right!\" they groaned one night."],
            ["\"Remember what Mr. Ray says about patience,\" {{FATHER}} reminded.", "{{CHILD}} sighed, took a breath, and tried once more.", "This time — slowly — the left hand played three correct bass notes."],
            ["Week three brought a new challenge: playing both hands together.", "Right hand melody, left hand bass. A musical conversation.", "{{CHILD}}'s brain felt like it was trying to pat their head and rub their tummy."],
            ["The first attempts were terrible — hands fought each other.", "Notes clashed, timing crumbled, and {{CHILD}} wanted to quit.", "But something inside said, \"Try one more time.\""],
            ["And that one more time... the hands aligned for four whole notes.", "It was messy and slow, but both hands worked TOGETHER.", "{{CHILD}} gasped and looked at Mr. Ray with shining eyes."],
            ["\"There it is!\" Mr. Ray clapped. \"That's the moment!\"", "\"The moment when patience turns into progress.\"", "{{CHILD}} played those four notes again, better this time."],
            ["Practice changed after that. {{CHILD}} was more focused, more calm.", "Instead of rushing through songs, they savored each note.", "The keyboard at home became a place of peaceful concentration."],
            ["A month in, {{CHILD}} could play \"Twinkle\" with both hands.", "Not perfect — a few fumbled notes here and there.", "But it was real music, made by real determined fingers."],
            ["Mr. Ray taught a new song: \"Ode to Joy\" by Beethoven.", "The melody was beautiful and filled {{CHILD}} with emotion.", "\"Beethoven was patient too — he wrote this while deaf!\""],
            ["That fact amazed {{CHILD}}. Deaf, and he still made music?", "\"He felt the vibrations and heard with his heart,\" Mr. Ray said.", "{{CHILD}} played the first line and tried to feel it, not just hear it."],
            ["Weeks of practice followed. The song grew longer, more complex.", "Some sections took twenty attempts to get right.", "But {{CHILD}} didn't get frustrated — they got fascinated."],
            ["\"Each mistake tells you what your fingers need to learn,\" Mr. Ray said.", "{{CHILD}} started treating mistakes as friendly teachers.", "\"Oh, my pinky was too slow there. Let me help it.\""],
            ["The school announced a spring music recital.", "\"Would you like to perform?\" Mr. Ray asked carefully.", "{{CHILD}} felt nervous but nodded. \"I think I'm ready.\""],
            ["Practice intensified. \"Ode to Joy\" had to be memorized.", "{{CHILD}} played it walking to school, tapping keys on their legs.", "The melody lived inside them now."],
            ["Recital day arrived wrapped in beautiful springtime sunshine.", "{{CHILD}} wore their best outfit and shiny shoes.", "The school auditorium had a real grand piano on stage!"],
            ["Sitting at the grand piano felt different — bigger, more serious.", "The keys were heavier, the sound was richer.", "{{CHILD}} placed their hands and waited for the signal."],
            ["The first note filled the whole auditorium.", "It was louder and more beautiful than any practice session.", "{{CHILD}} poured their heart into every single note."],
            ["Patience paid off — fingers found every key without stumbling.", "The melody soared through the room like a bird set free.", "In the audience, {{MOTHER}} pressed her hand to her heart."],
            ["The last note hung in the air like a held breath.", "Then — applause, warm and loud and wonderful.", "{{CHILD}} stood and bowed, legs trembling with happy relief."],
            ["Mr. Ray met them backstage with the biggest smile.", "\"That was patient, beautiful, heartfelt playing,\" he said.", "\"I'm so proud of how far you've come.\""],
            ["{{FATHER}} swung {{CHILD}} around in a celebratory circle.", "\"My little musician! That was absolutely incredible!\"", "{{CHILD}} laughed and felt like they could fly."],
            ["In the car home, the melody replayed in {{CHILD}}'s head.", "Each note bringing back the feeling of the stage lights.", "\"Can I learn guitar next?\" {{CHILD}} asked dreamily."],
            ["\"Let's master piano first,\" {{MOTHER}} said gently but firmly.", "\"One instrument at a time. Remember — patience.\"", "{{CHILD}} smiled. Patience had become their superpower."],
            ["At home, {{CHILD}} sat at the old keyboard with new respect.", "It wasn't a grand piano, but it was where the magic started.", "\"Thank you for being patient with me,\" {{CHILD}} told the keys."],
            ["After dinner, {{CHILD}} played \"Ode to Joy\" for the whole family.", "Even the dog sat and listened with ears perked up.", "\"The dog is a music fan!\" {{FATHER}} joked."],
            ["Bedtime came with a warm bath and clean pajamas.", "\"What did music teach you?\" {{MOTHER}} asked at tuck-in.", "\"That the best things come to those who practice,\" said {{CHILD}}."],
            ["\"And?\" {{MOTHER}} prompted. \"And that patience isn't waiting — it's trying.\"", "{{MOTHER}} kissed {{CHILD}}'s forehead. \"That's the wisest thing I've heard.\"", "{{CHILD}} smiled and pulled the blanket up to their chin."],
            ["The bedroom was quiet except for distant cricket songs.", "Nature's own little orchestra played outside the window.", "{{CHILD}} listened and found patterns in the chirping."],
            ["\"Even crickets practice their music,\" {{CHILD}} whispered.", "They hummed \"Ode to Joy\" softly, barely above a breath.", "The melody wrapped around them like a musical blanket."],
            ["Sleep arrived like a slow, gentle crescendo.", "Quiet at first, then deeper and more peaceful.", "The perfect rhythm of rest after a day of music."],
            ["In dreams, {{CHILD}} played a piano made of starlight.", "Each key sent a different colored light into the sky.", "The audience was the moon and all the twinkling stars."],
            ["Dream-music was the sound of patience turned into beauty.", "No rushing, no frustration — just pure, flowing melody.", "{{CHILD}} played and the universe listened."],
            ["The dream-piano floated on a cloud of applause.", "Below, {{CHILD}} could see their bedroom, their keyboard, their life.", "Everything connected by the invisible thread of music."],
            ["Morning would bring new notes to learn and new songs to try.", "But tonight, sleep was the most beautiful song.", "A lullaby composed by a day well-practiced."],
            ["The keyboard sat under its dust cover, dreaming its own dreams.", "Of grand concerts and little fingers and slow, patient progress.", "Tomorrow it would wake and make music again."],
            ["{{CHILD}}'s fingers rested peacefully on the pillow.", "Fingers that had learned to be patient, precise, and powerful.", "Fingers that turned frustration into beautiful sound."],
            ["The night was full of quiet music — heartbeats and breathing.", "The most natural rhythm there is.", "Patient, steady, and exactly right."],
            ["Goodnight, little musician. The keys are waiting for you.", "Play slowly, play patiently, play with your whole heart.", "And the music will always, always come."]
        ]
    },

    {
        id: "little-scientist", file: "littleScientist", title: "{{CHILD}}'s Science Lab", emoji: "🧪",
        theme: "Skill Stories", lesson: "Curiosity", coverColor: "#74B9FF",
        description: "Explore the amazing world of science with {{CHILD}} and discover that curiosity is a superpower!",
        pages: [
            ["{{CHILD}} put on safety goggles that were way too big for their face.", "The kitchen table was covered in cups, spoons, and ingredients.", "\"Today, we're scientists!\" announced {{MOTHER}} with a lab-coat flourish."],
            ["The first experiment: making a volcano with baking soda and vinegar!", "{{CHILD}} shaped a mound of clay around a plastic cup.", "\"The lava will come out of the top,\" they explained."],
            ["A spoonful of baking soda went into the cup.", "\"Ready?\" asked {{CHILD}}, holding the vinegar bottle high.", "\"Ready!\" said {{MOTHER}}, phone camera pointed."],
            ["FIZZ! WHOOSH! Bubbly foam erupted from the cup!", "It spilled over the clay volcano and spread across the table.", "\"IT'S ERUPTING! IT'S ERUPTING!\" {{CHILD}} shrieked with delight."],
            ["\"But WHY does it fizz?\" {{CHILD}} asked, staring at the bubbles.", "\"That's the best question a scientist can ask,\" said {{MOTHER}}.", "\"The two chemicals react and create a gas — carbon dioxide!\""],
            ["{{CHILD}} wanted to try again with more baking soda.", "The second eruption was bigger — foam everywhere!", "\"More reactant equals more reaction!\" {{CHILD}} declared."],
            ["Cleanup was part of science too — proper lab maintenance.", "{{CHILD}} wiped the table and organized the supplies.", "\"Scientists always clean their lab before the next experiment.\""],
            ["Experiment two: invisible ink with lemon juice!", "{{CHILD}} squeezed a lemon into a bowl and dipped a cotton swab.", "Secret letters appeared on white paper — invisible to the eye."],
            ["\"Now hold it near the warm lamp,\" {{MOTHER}} instructed.", "Slowly, the letters turned brown and appeared like magic!", "\"HELLO\" was written in ghostly brown letters."],
            ["\"The heat makes the lemon juice oxidize,\" {{MOTHER}} explained.", "\"Oxi-what?\" asked {{CHILD}}. \"It means it reacts with the air.\"", "{{CHILD}} scribbled that word in their science notebook: OXIDIZE."],
            ["The science notebook was getting full of observations.", "Drawings of volcanoes, invisible ink, and question marks.", "So many questions — that was the best part."],
            ["Experiment three: density towers with liquids from the kitchen.", "Honey on the bottom, then dish soap, then water, then oil.", "Each layer sat perfectly on top of the one below."],
            ["\"Why don't they mix?\" {{CHILD}} peered closely at the jar.", "\"Each liquid has a different density — how heavy it is for its size.\"", "{{CHILD}} dropped a grape in — it sank to the honey layer!"],
            ["A cork floated right on top of the oil.", "A button sank to the soap layer.", "\"Different objects have different densities too!\" gasped {{CHILD}}."],
            ["\"What about a raisin?\" {{CHILD}} dropped one in experimentally.", "It sank to the water layer — right in the middle!", "\"Science is just asking questions and finding answers.\""],
            ["{{FATHER}} came home to find the kitchen transformed into a lab.", "\"What's all this?\" he asked, dodging a foam volcano.", "\"SCIENCE!\" {{CHILD}} answered, adjusting their giant goggles."],
            ["{{CHILD}} demonstrated each experiment for {{FATHER}}.", "The volcano, the invisible ink, the density tower.", "{{FATHER}} asked questions and {{CHILD}} answered like a real professor."],
            ["\"I want to know why the sky is blue,\" {{CHILD}} said at dinner.", "\"That's called Rayleigh scattering,\" {{MOTHER}} began.", "{{CHILD}} listened with wide eyes, absorbing every word."],
            ["After dinner, {{CHILD}} looked up at the actual sky.", "The sunset was orange, pink, and purple.", "\"The light scatters differently when the sun is low!\" they realized."],
            ["A magnifying glass became {{CHILD}}'s constant companion.", "Ants on the sidewalk, leaves on trees, patterns in fabric.", "Everything looked different and magical up close."],
            ["\"The leaf has tiny veins like a road map!\" {{CHILD}} observed.", "They sketched the leaf pattern in their science notebook.", "Each observation led to three more questions."],
            ["The next experiment was the hardest: growing crystals.", "Sugar dissolved in hot water, poured into a jar with a string.", "\"Now we wait three whole days,\" {{MOTHER}} said."],
            ["Waiting was HARD. {{CHILD}} checked the jar every hour.", "\"Has anything happened yet?\" \"Not yet.\" \"How about now?\"", "\"Scientists need patience too,\" {{MOTHER}} reminded."],
            ["On day two, tiny sparkles appeared on the string!", "\"CRYSTALS! I see crystals!\" {{CHILD}} pressed their nose to the glass.", "\"They're growing! They're actually growing!\""],
            ["By day three, beautiful sugar crystals covered the string.", "They caught the light and sparkled like diamonds.", "\"I grew crystals. I actually grew real crystals,\" {{CHILD}} whispered in awe."],
            ["The crystal was carefully removed and examined under the magnifying glass.", "Perfect geometric shapes, repeated over and over.", "\"Nature builds with math,\" {{CHILD}} said, amazed."],
            ["{{CHILD}} started a crystal collection in a shoebox.", "Salt crystals, sugar crystals, and alum crystals from the craft store.", "Each one was labeled with its name and how it was grown."],
            ["A rainy day brought the perfect experiment: rain gauge building.", "A plastic bottle, some tape, a ruler — simple materials.", "{{CHILD}} placed it in the garden and waited for rainfall data."],
            ["\"Real scientists collect data over time,\" {{MOTHER}} explained.", "{{CHILD}} created a chart: Day 1 — 0.5 inches. Day 2 — 0.", "\"I'm tracking weather patterns!\" they said proudly."],
            ["The science notebook was almost full.", "Volcanos, crystals, density, invisible ink, rainfall.", "Each page was a doorway to understanding the world."],
            ["\"Why do birds fly?\" \"Why do stars twinkle?\" \"Why is water wet?\"", "Questions tumbled out of {{CHILD}} like waterfalls.", "\"Never stop asking why,\" {{MOTHER}} said. \"That's your superpower.\""],
            ["{{CHILD}} decided to present their experiments to the family.", "A real science fair on the dining table!", "Poster boards, labeled jars, and a volcano demonstration."],
            ["The presentation was impressive — clear, excited, and curious.", "{{FATHER}} asked tough questions and {{CHILD}} answered them all.", "\"I don't know that one... but I'll find out!\" was the best answer."],
            ["\"Not knowing is the beginning of every discovery,\" {{MOTHER}} said.", "{{CHILD}} wrote that in the notebook in big, capital letters.", "It was the most important scientific principle of all."],
            ["Before bed, {{CHILD}} placed the crystal on the nightstand.", "It caught the lamplight and threw tiny rainbows on the wall.", "\"Even my nightlight does science,\" {{CHILD}} smiled."],
            ["\"What was your favorite experiment?\" {{MOTHER}} asked at tuck-in.", "{{CHILD}} thought hard. \"The crystals, because I had to wait.\"", "\"And waiting taught me that the best things grow slowly.\""],
            ["{{MOTHER}} tucked the blankets around {{CHILD}} like a lab coat.", "\"Tomorrow's experiment: what happens to plants in the dark?\"", "{{CHILD}}'s eyes lit up with curiosity even as sleep approached."],
            ["The science notebook poked out from under the pillow.", "Full of questions, drawings, and the beginning of understanding.", "Every page was proof that curiosity makes the world bigger."],
            ["Sleep came like a gentle reaction — slow, warm, and natural.", "{{CHILD}}'s mind was still humming with wonder.", "Behind closed eyelids, experiments played in vivid color."],
            ["In dreams, {{CHILD}} wore a real lab coat and safety goggles.", "A laboratory full of bubbling beakers and spinning gadgets.", "\"What should we discover tonight?\" asked a dream-voice."],
            ["Dream-experiments had no limits — chemistry in zero gravity!", "Colors mixing in mid-air, crystals growing in seconds.", "The whole universe was a science lab waiting to be explored."],
            ["A dream-telescope showed planets made of different elements.", "A purple one of silicon, a golden one of copper.", "\"Everything in the universe follows rules,\" dream-{{CHILD}} realized."],
            ["The dream slowly dissolved like sugar in warm water.", "Questions faded into peaceful, restful quiet.", "Tomorrow would bring new hypotheses to test."],
            ["The crystal on the nightstand twinkled in the moonlight.", "A tiny monument to patience, curiosity, and wonder.", "It would be there in the morning, sparkling with possibility."],
            ["Outside, the rain gauge collected data in the dark.", "Clouds performed their own weather experiments overhead.", "Nature — the greatest scientist — never stopped working."],
            ["And inside, the littlest scientist slept deeply.", "Dreaming of questions, discoveries, and beautiful reactions.", "Curiosity resting, gathering strength for another day."],
            ["The goggles sat on the desk, waiting faithfully.", "The notebook waited. The magnifying glass waited.", "All the tools of wonder, ready for tomorrow."],
            ["Science is everywhere — in raindrops, in bread rising, in starlight.", "And the best scientists are the ones who never stop asking why.", "{{CHILD}} was one of those scientists for sure."],
            ["The house settled into its nighttime quiet.", "Even the volcano experiment had stopped fizzing.", "But curiosity? That never stops. It just goes to sleep for a while."],
            ["Goodnight, little scientist. The world is full of wonders.", "Keep asking questions. Keep watching closely. Keep being amazed.", "Tomorrow's discovery is waiting — and it's going to be incredible."]
        ]
    },

    {
        id: "junior-chef", file: "juniorChef", title: "{{CHILD}}'s Chef Adventure", emoji: "🍳",
        theme: "Skill Stories", lesson: "Independence", coverColor: "#FF7675",
        description: "Watch {{CHILD}} cook up confidence and independence in the kitchen!",
        pages: [
            ["{{CHILD}} stood on a sturdy step stool, wearing a tiny chef hat.", "A real apron was tied around their waist — it had their name on it!", "\"Today, you're the head chef,\" said {{FATHER}} with a salute."],
            ["The refrigerator was open, revealing colorful ingredients.", "Tomatoes as red as fire trucks, lettuce as green as grass.", "\"First, a chef inspects their ingredients,\" {{CHILD}} announced seriously."],
            ["\"We're making a salad, soup, and fruit cups — all by ourselves!\"", "Well, with {{FATHER}} watching from the counter, just in case.", "But the chopping, mixing, and tasting? All {{CHILD}}."],
            ["Washing vegetables came first — every piece under cold water.", "{{CHILD}} scrubbed each tomato gently like giving it a tiny bath.", "\"Clean ingredients make healthy food,\" they said wisely."],
            ["The butter knife was the designated cutting tool — safe but effective.", "{{CHILD}} cut a banana into round coins, slow and steady.", "Each slice was examined for thickness. \"Pretty good!\" they nodded."],
            ["Lettuce leaves were torn by hand — rip, rip, rip.", "\"Why don't we cut lettuce?\" {{CHILD}} asked.", "\"Cutting makes it brown. Tearing keeps it fresh,\" {{FATHER}} explained."],
            ["Cherry tomatoes were halved with extra careful hands.", "\"These are slippery little guys!\" {{CHILD}} laughed.", "Each tomato half went into the big wooden salad bowl."],
            ["Cucumber slices were next — cool, crisp, and perfect.", "{{CHILD}} arranged them around the edge of the bowl like a wreath.", "\"Presentation matters!\" they said, sounding very professional."],
            ["The dressing was homemade: olive oil, lemon, salt, and pepper.", "{{CHILD}} poured each ingredient into a small jar.", "\"Now shake!\" They shook the jar like a maraca — up, down, all around!"],
            ["The dressing drizzled over the salad in golden streams.", "{{CHILD}} tossed the salad gently with wooden spoons.", "\"My first salad, made 100% by ME,\" they said proudly."],
            ["Soup was next — tomato soup from real tomatoes.", "{{FATHER}} helped with the hot stove, but {{CHILD}} did the rest.", "Onions, garlic, tomatoes, and broth — each added by little hands."],
            ["\"Stir slowly so it doesn't splash,\" {{FATHER}} coached from nearby.", "The wooden spoon circled the pot like a tiny canoe in a red lake.", "Steam rose and brought the most delicious tomato smell."],
            ["\"Can I add basil?\" {{CHILD}} asked, holding a green leaf.", "\"Absolutely — basil is tomato's best friend.\"", "The torn basil leaves floated on the surface like little boats."],
            ["While the soup simmered, fruit cups were assembled.", "Strawberries, blueberries, and kiwi in small glass cups.", "{{CHILD}} used a melon baller to scoop perfect little spheres."],
            ["\"The fruit cup needs a topping,\" {{CHILD}} decided.", "A spoonful of yogurt and a drizzle of honey on each cup.", "\"It's like a tiny sundae but with fruit!\" they beamed."],
            ["The table was set by {{CHILD}} — plates, napkins, and glasses.", "Everything was placed with thought and care.", "\"A chef also sets a beautiful table,\" {{CHILD}} explained."],
            ["{{MOTHER}} arrived home to find a fully prepared dinner.", "\"WHAT?! WHO COOKED ALL THIS?\" she gasped dramatically.", "\"Chef {{CHILD}}, at your service!\" They bowed with a flourish."],
            ["The family sat down and {{CHILD}} served each dish.", "Salad first, then soup in careful spoonfuls, then fruit cups.", "\"Please enjoy, and remember to compliment the chef.\""],
            ["The first bite of salad made {{MOTHER}} close her eyes.", "\"This dressing is incredible! What's your secret ingredient?\"", "\"Love,\" said {{CHILD}} simply. \"And also lemon.\""],
            ["The tomato soup was rich, warm, and perfectly seasoned.", "\"This is restaurant quality!\" {{FATHER}} said, not exaggerating.", "{{CHILD}} glowed brighter than the kitchen lights."],
            ["Fruit cups were the finale — refreshing and beautiful.", "\"Even the plating looks professional,\" {{MOTHER}} admired.", "{{CHILD}} had stacked the berries in a little pyramid."],
            ["\"I did almost everything myself,\" {{CHILD}} said quietly.", "The realization settled in — they were capable of real things.", "Independence felt like the warmest, proudest feeling ever."],
            ["\"You know what the best part is?\" {{FATHER}} asked.", "\"You didn't need anyone to tell you what to do next.\"", "{{CHILD}} nodded. They had followed the recipe AND their instincts."],
            ["After dinner, {{CHILD}} insisted on helping with dishes.", "\"A real chef cleans their own kitchen,\" they said firmly.", "Suds flew and dishes sparkled under their determined scrubbing."],
            ["The leftover soup was stored in containers by {{CHILD}}.", "Labels were written in crayon: \"{{CHILD}}'s Tomato Soup — Day 1.\"", "\"We'll have it for lunch tomorrow!\" they planned."],
            ["{{CHILD}} started writing their own recipe book.", "\"{{CHILD}}'s Kitchen\" was drawn on the cover in big letters.", "The salad recipe was the first entry, with drawings of each step."],
            ["\"What should I cook next?\" {{CHILD}} flipped through a cookbook.", "Pasta? Stir-fry? Pancakes? The options were endless!", "\"Start simple and build up,\"{{FATHER}} advised wisely."],
            ["\"Pancakes for breakfast tomorrow!\" {{CHILD}} decided.", "The ingredients were set out on the counter that very night.", "Flour, eggs, milk, and a secret ingredient: cinnamon."],
            ["Bath time was filled with plans for the morning meal.", "\"I'll need to wake up early to make the batter,\" {{CHILD}} said.", "\"A real chef is always prepared,\" they added, scrubbing behind ears."],
            ["In pajamas, {{CHILD}} reviewed the pancake recipe one last time.", "Ingredients, measurements, steps — all memorized.", "\"I can do this by myself,\" they whispered confidently."],
            ["{{MOTHER}} sat on the bed for tuck-in time.", "\"You fed the whole family tonight, all by yourself.\"", "\"Well, {{FATHER}} helped with the hot stove,\" {{CHILD}} said honestly."],
            ["\"But the ideas, the chopping, the seasoning — that was all you.\"", "{{CHILD}} snuggled deeper into the pillow with a satisfied sigh.", "Doing things on your own felt like growing up, but in a warm way."],
            ["\"Are you scared to cook alone?\" {{MOTHER}} asked softly.", "\"A little bit,\" {{CHILD}} admitted. \"But I know I can figure it out.\"", "\"That's exactly what independence means,\" {{MOTHER}} smiled."],
            ["The chef hat was hung on the bedpost like a trophy.", "The apron with their name was folded on the chair.", "Tools of a chef who was learning to stand on their own."],
            ["\"Goodnight, Chef {{CHILD}},\" {{MOTHER}} kissed their forehead.", "\"Goodnight, my favorite taste-tester,\" {{CHILD}} replied.", "The room smelled faintly of tomato soup and happiness."],
            ["Stars outside looked like sprinkled salt on a dark tablecloth.", "{{CHILD}} imagined cooking underneath them someday.", "A chef's table under the stars — what a dream!"],
            ["Sleep arrived slowly, like soup coming to a simmer.", "Warm, gradual, and inevitable in the best possible way.", "{{CHILD}}'s breathing became as rhythmic as stirring."],
            ["Dreams were full of giant kitchens with endless ingredients.", "Dream-{{CHILD}} cooked for a hundred guests, calm and confident.", "Every dish was perfect because every chef believes in themselves."],
            ["In the dream kitchen, {{CHILD}} reached things without a step stool.", "Tall enough, skilled enough, independent enough.", "The dream-guests cheered and asked for seconds."],
            ["The dream faded like steam from a cooling pot.", "Warm, misty, and comforting.", "Tomorrow's pancakes were already sizzling in {{CHILD}}'s imagination."],
            ["The recipe book sat on the kitchen table, waiting.", "Its empty pages were hungry for new recipes and adventures.", "Each one would be another step toward independence."],
            ["{{CHILD}} rolled over and hugged the blanket.", "Strong little hands that had chopped, stirred, and served.", "Hands that were learning they could do amazing things alone."],
            ["The kitchen nightlight glowed amber — like melted butter.", "Every surface was clean, every tool was put away.", "A chef's kitchen, ready for tomorrow's early morning pancakes."],
            ["Outside, the world slept under a blanket of quiet.", "Inside, a young chef dreamed of flavors and confidence.", "Independence isn't doing everything alone — it's knowing you CAN."],
            ["The cinnamon sat on the counter, dreaming of pancake batter.", "Flour waited in the canister. Eggs rested in the fridge.", "All the ingredients of tomorrow, ready for {{CHILD}}'s capable hands."],
            ["Night deepened and the house settled with soft creaks.", "{{CHILD}} slept the deep sleep of someone who worked hard.", "Fed the family, cleaned the kitchen, planned tomorrow's meal."],
            ["The dream-kitchen slowly melted into warm darkness.", "No more stirring, no more chopping — just peaceful rest.", "Even chefs need to recharge their energy for the next day."],
            ["Morning would come with a mission: perfect pancakes.", "But tonight, sleep was the most important ingredient.", "Rest, dream, and wake up ready to cook up independence."],
            ["The chef hat swayed gently on the bedpost.", "A tiny crown for a tiny chef with big capabilities.", "Tomorrow, that hat would be worn again with earned confidence."],
            ["Goodnight, Chef {{CHILD}}. Your kitchen awaits.", "Every recipe is a new adventure in doing things yourself.", "Sleep well, dream of flavors, and wake up ready to create."]
        ]
    },

    {
        id: "young-gardener", file: "youngGardener", title: "{{CHILD}}'s Garden", emoji: "🌻",
        theme: "Skill Stories", lesson: "Responsibility", coverColor: "#55EFC4",
        description: "Grow beautiful things with {{CHILD}} and learn about responsibility along the way!",
        pages: [
            ["Spring had arrived and the backyard was waking up.", "{{CHILD}} knelt in the dirt wearing old jeans and rain boots.", "\"My very own garden patch,\" they said, smoothing the dark soil."],
            ["{{MOTHER}} brought out tiny seed packets — sunflower, marigold, and pea.", "Each packet had a colorful picture of what would grow.", "\"These tiny seeds will become BIG plants if you take care of them.\""],
            ["\"Taking care of living things is a big responsibility,\" {{MOTHER}} added.", "{{CHILD}} nodded seriously, ready for the challenge.", "They opened the sunflower packet — seeds as big as fingernails."],
            ["Small holes were poked in the dirt with one finger.", "Each seed was placed in its own hole, then covered gently.", "\"Sleep tight, little seeds,\" {{CHILD}} whispered to the ground."],
            ["The watering can rained softly over the planted area.", "\"Not too much water — seeds can drown,\" {{MOTHER}} warned.", "{{CHILD}} measured carefully: enough to be damp, not soggy."],
            ["A hand-drawn sign was pushed into the soil: \"{{CHILD}}'s Garden.\"", "Underneath it said, \"Please grow! Love, your gardener.\"", "The sign had drawings of giant sunflowers on it."],
            ["Day one passed. Day two. Day three. Nothing.", "{{CHILD}} checked the patch every single morning.", "\"Are they ever going to grow?\" they asked impatiently."],
            ["\"Seeds need time underground before they come up,\" {{MOTHER}} said.", "\"Your job is to keep watering and trust the process.\"", "{{CHILD}} watered dutifully, even though nothing was visible."],
            ["On day five, a tiny green sprout broke through the soil!", "\"IT'S ALIVE!\" {{CHILD}} screamed, running through the house.", "Everyone came outside to see the tiny miracle."],
            ["The sprout was barely an inch tall, with two baby leaves.", "So small, so fragile, and absolutely amazing.", "\"I grew that,\" {{CHILD}} said quietly, full of wonder."],
            ["More sprouts appeared over the next few days.", "A row of tiny green soldiers standing at attention.", "{{CHILD}} counted them every morning: one, two, three... seven!"],
            ["Watering became the most important part of {{CHILD}}'s routine.", "Before breakfast, before play — the plants came first.", "\"They can't water themselves,\" {{CHILD}} explained to their toys."],
            ["One morning, a sprout was bent sideways from the wind.", "{{CHILD}} gently propped it up with a small stick and string.", "\"There you go, little one. I'll protect you.\""],
            ["The marigold seedlings had fuzzy leaves that felt like velvet.", "The peas were already reaching tendrils toward the fence.", "Each plant had its own personality and growing style."],
            ["{{CHILD}} started a garden journal with dates and drawings.", "\"Day 12: Sunflower is 3 inches. Marigold has 4 leaves.\"", "Every detail was recorded with scientific precision."],
            ["A hot day threatened to dry out the garden.", "{{CHILD}} watered twice — morning and late afternoon.", "\"Don't worry, plants. I've got you,\" they promised."],
            ["Something was eating the pea leaves! Tiny holes appeared overnight.", "{{CHILD}} and {{MOTHER}} investigated: slugs!", "A ring of crushed eggshells around the peas kept the slugs away."],
            ["\"Being responsible means solving problems, not giving up,\" {{MOTHER}} said.", "{{CHILD}} felt proud of finding the slug solution.", "The pea plants bounced back within a week."],
            ["The sunflowers grew taller and taller — past {{CHILD}}'s knees.", "Thick stems, broad leaves, reaching toward the sun.", "\"They're almost as tall as me!\" {{CHILD}} measured back to back."],
            ["Marigolds burst into orange and yellow blooms.", "The garden was finally COLORFUL — not just green.", "Bees arrived and buzzed happily around the open petals."],
            ["{{CHILD}} learned about bees and pollination.", "\"The bees help the flowers make seeds for next year!\"", "\"Everyone has a job in the garden — even the bugs.\""],
            ["A week without rain tested {{CHILD}}'s commitment.", "\"I'm tired of watering,\" they sighed one hot afternoon.", "\"Your plants are counting on you,\" {{FATHER}} reminded gently."],
            ["{{CHILD}} picked up the watering can and went outside.", "The droopy plants perked up as water touched their roots.", "\"See? They needed you,\" {{FATHER}} said from the window."],
            ["That moment changed something inside {{CHILD}}.", "Responsibility wasn't just a chore — it was being NEEDED.", "The plants depended on them, and that felt important."],
            ["The biggest sunflower grew taller than {{CHILD}}!", "A massive flower head developed, following the sun across the sky.", "\"It looks at the sun the way I look at ice cream,\" {{CHILD}} joked."],
            ["The peas produced actual pea pods — tiny green packages.", "{{CHILD}} picked one and opened it — perfect little peas inside!", "The first taste: sweet, fresh, and nothing like store-bought."],
            ["\"I grew food! Real food that I can eat!\" {{CHILD}} was amazed.", "They ran inside with a handful of peas for the family.", "\"Try these — they came from MY garden!\""],
            ["Everyone agreed the peas were the best they'd ever tasted.", "\"Because you grew them with love and responsibility,\" {{MOTHER}} said.", "{{CHILD}} stood a little taller after that comment."],
            ["The garden attracted butterflies — orange, yellow, and white.", "{{CHILD}} sat perfectly still and one landed on their shoe.", "Neither of them moved. It was the most magical moment."],
            ["A neighbor's child came to see the garden.", "{{CHILD}} explained everything: watering, sunlight, slug protection.", "\"Can I grow a garden too?\" the neighbor asked."],
            ["\"Yes! I'll give you some seeds!\" {{CHILD}} scooped out sunflower seeds.", "Teaching someone else felt wonderful.", "Responsibility was spreading like flowers in the wind."],
            ["The sunflower head drooped with the weight of ripening seeds.", "\"It's time to harvest,\" {{MOTHER}} showed.", "{{CHILD}} carefully collected seeds into an envelope."],
            ["\"These seeds will become next year's sunflowers,\" {{CHILD}} realized.", "The cycle was complete: seed, sprout, flower, seed again.", "\"That's the most amazing thing I've ever learned.\""],
            ["As summer ended, the marigolds started to fade.", "{{CHILD}} felt sad seeing their flowers droop.", "\"Everything has a season,\" {{MOTHER}} said softly. \"That's nature.\""],
            ["{{CHILD}} collected the last marigold seeds and stored them carefully.", "\"I'll plant you again next spring. I promise.\"", "The empty garden bed was covered with leaves for winter."],
            ["Looking at the seed envelopes felt like holding the future.", "Sunflower, marigold, and pea seeds — all from {{CHILD}}'s garden.", "Grown with responsibility, patience, and love."],
            ["The garden journal had filled up — 60 entries, front and back.", "From \"Day 1: Planted seeds\" to \"Day 60: Harvested everything.\"", "A complete record of growth — the garden's AND {{CHILD}}'s."],
            ["At bedtime, {{CHILD}} placed the seed envelope on the shelf.", "\"These seeds are counting on me to plant them in spring.\"", "Responsibility didn't end when the season changed."],
            ["\"What did your garden teach you?\" {{MOTHER}} asked at tuck-in.", "\"That taking care of something makes it — and you — grow.\"", "{{MOTHER}} hugged {{CHILD}} tightly, so proud of those words."],
            ["\"And that slugs are sneaky but eggshells are sneakier,\" {{CHILD}} added.", "They both laughed and the room filled with warmth.", "The best lessons come with a pinch of humor."],
            ["Rain began tapping on the window — perfect garden weather.", "{{CHILD}} listened and imagined the empty bed drinking it up.", "\"Getting ready for next year's seeds,\" they murmured."],
            ["Sleep came like a seed settling into warm, dark soil.", "Invisible at first, but growing steadily underground.", "The most natural, responsible rhythm in the world."],
            ["Dreams were green and golden — a garden the size of a field.", "Sunflowers tall as trees, pea vines reaching the clouds.", "{{CHILD}} walked through their dream-garden, touching every leaf."],
            ["\"Thank you for taking care of us,\" the dream-flowers whispered.", "\"Thank you for teaching me responsibility,\" {{CHILD}} whispered back.", "In dreams, gardens and gardeners understand each other perfectly."],
            ["The dream-rain was warm and smelled like wet earth.", "Seeds sprouted in fast-forward — a time-lapse of wonder.", "Buds opened, fruits ripened, and the garden sang."],
            ["Morning would bring homework, breakfast, and ordinary things.", "But the seed envelopes on the shelf held extraordinary promises.", "Promises that {{CHILD}} would keep, because that's what responsibility means."],
            ["Outside, the rain nourished the sleeping garden bed.", "Inside, the little gardener nourished their sleeping body.", "Both resting, both growing, both getting ready for spring."],
            ["The garden journal sat on the desk, closed and satisfied.", "Next year's journal was already a fresh, empty notebook.", "Blank pages waiting for new measurements, new drawings, new growth."],
            ["{{CHILD}}'s rain boots stood by the back door, muddy and well-used.", "They'd walked through the garden a thousand times this season.", "A thousand steps of dedication, care, and responsibility."],
            ["Goodnight, little gardener. Your seeds are safe and dreaming.", "Spring will come, and so will the flowers, and so will you.", "Rest now — growing is hard work, and you've earned your sleep."]
        ]
    },

    {
        id: "star-coder", file: "starCoder", title: "{{CHILD}}'s Code Quest", emoji: "💻",
        theme: "Skill Stories", lesson: "Persistence", coverColor: "#2D3436",
        description: "Join {{CHILD}} on a coding adventure where bugs become puzzles and persistence wins!",
        pages: [
            ["The computer screen glowed blue in the dimming room.", "{{CHILD}} clicked on a colorful icon: \"KidCode — Learn to Code!\"", "A friendly robot appeared and waved. \"Hello, future coder!\""],
            ["\"I'm Byte,\" said the robot. \"I'll teach you how to talk to computers!\"", "The first lesson showed colored blocks that snapped together.", "\"Each block is an instruction. Computers follow instructions exactly.\""],
            ["{{CHILD}} dragged a \"Move Forward\" block onto the screen.", "A tiny character on a grid took one step forward.", "\"I told it what to do — and it LISTENED!\" {{CHILD}}'s eyes shone."],
            ["Three more \"Move Forward\" blocks got the character to a star.", "\"Level 1 Complete!\" the screen flashed with virtual confetti.", "\"That was easy!\" said {{CHILD}}, feeling like a genius already."],
            ["Level 2 needed a turn — \"Turn Right\" then \"Move Forward.\"", "{{CHILD}} clicked blocks and the character navigated a corner.", "\"I'm making a little robot walk around!\" they laughed."],
            ["By level 5, the puzzles got harder — obstacles appeared on the grid.", "The character had to find a winding path around walls.", "{{CHILD}} scratched their head and studied the grid carefully."],
            ["The first attempt hit a wall — literally.", "\"Oops!\" said Byte. \"That's called a bug. Can you fix it?\"", "{{CHILD}} removed the wrong block and tried a different direction."],
            ["Success! The character zigzagged perfectly around every wall.", "\"Debugging is just finding and fixing mistakes,\" Byte explained.", "\"I'm a debugger!\" {{CHILD}} announced proudly."],
            ["Level 10 introduced \"loops\" — repeating actions.", "Instead of five \"Move Forward\" blocks, one loop said \"Repeat 5 times.\"", "\"That's so much more efficient!\" {{CHILD}} was impressed."],
            ["The loop concept opened up a whole new world.", "Complex mazes became manageable with repeat blocks.", "\"Programmers are lazy in a smart way,\" Byte joked."],
            ["{{CHILD}} wanted to show {{FATHER}} what they'd learned.", "\"Watch this — I can make the character dance!\"", "A loop of move, turn, move, turn created a spinning square dance."],
            ["\"You're already thinking like a programmer,\" {{FATHER}} said, amazed.", "{{CHILD}} beamed. \"I want to make my OWN game next!\"", "\"Games start with small steps — just like your character.\""],
            ["The next module taught \"conditionals\" — IF this, THEN that.", "\"IF path is blocked, THEN turn right,\" {{CHILD}} programmed.", "The character could now make its own decisions!"],
            ["\"It's like teaching the computer to think!\" {{CHILD}} gasped.", "Byte nodded. \"You're giving it rules to follow, no matter what.\"", "The character now solved simple mazes ALL BY ITSELF."],
            ["But level 20 was brutal. Nothing {{CHILD}} tried worked.", "The character ran into walls, went in circles, got stuck.", "\"This is IMPOSSIBLE,\" {{CHILD}} groaned, pushing back from the desk."],
            ["Twenty minutes of frustration. The screen seemed to mock them.", "{{CHILD}} wanted to close the program and play something else.", "But Byte's words echoed: \"Programmers are persistent people.\""],
            ["{{CHILD}} took a deep breath and looked at the puzzle fresh.", "\"What if I break it into smaller pieces?\" they thought.", "First: get to the corner. Then: navigate around the wall."],
            ["The first piece worked. Then the second. Then the third.", "Piece by piece, the solution came together like a jigsaw.", "\"LEVEL 20 COMPLETE!\" The screen exploded with stars."],
            ["{{CHILD}} jumped up from the chair and did a victory dance.", "\"I DIDN'T GIVE UP! I didn't give up!\" they chanted.", "That level taught more than coding — it taught persistence."],
            ["The next day, {{CHILD}} told friends about coding at school.", "\"You make a robot walk around by giving it instructions!\"", "Two friends asked if they could try it too."],
            ["After school, three kids sat around the computer together.", "{{CHILD}} taught them blocks, loops, and debugging.", "\"When it doesn't work, that's the fun part!\" they encouraged."],
            ["Teaching made {{CHILD}} understand coding even better.", "Explaining loops to someone else solidified the concept.", "\"To really learn something, teach it,\" {{MOTHER}} observed."],
            ["Level 25 introduced variables — storing and using data.", "\"score = 0\" and every star collected added 1.", "\"The computer remembers things just like my brain!\" {{CHILD}} said."],
            ["The program now tracked {{CHILD}}'s score across all levels.", "\"I have 847 points!\" they announced at dinner.", "\"Each point represents a problem you solved,\" {{FATHER}} noted."],
            ["A weekend coding marathon reached level 30: creating functions.", "A function was a set of moves they could name and reuse.", "{{CHILD}} created \"doSquareDance\" — their first named function!"],
            ["Functions made complex programs much shorter and cleaner.", "\"It's like having a recipe you can call by name,\" Byte said.", "The connection to real-life made everything click."],
            ["The most exciting moment came when {{CHILD}} made their first game.", "A simple maze game where a character collects stars.", "It was only 15 blocks long — but it WORKED."],
            ["{{CHILD}} let friends play their game on the tablet.", "\"You MADE this?!\" they said, completely amazed.", "\"Yes, and I can make it even better,\" {{CHILD}} said confidently."],
            ["Bugs appeared in the game — sometimes the score didn't update.", "{{CHILD}} debugged for an hour, checking each block.", "The missing piece: the score variable wasn't inside the loop!"],
            ["\"Found it!\" {{CHILD}} fixed the bug and tested again.", "Perfect! Every star added exactly one point now.", "Debugging felt like being a detective solving a mystery."],
            ["The coding journey had taught {{CHILD}} so many things.", "Patience when things don't work. Joy when they do.", "And the most important lesson: never, ever give up."],
            ["{{CHILD}} started a coding journal alongside the program.", "\"Day 1: Learned Move Forward. Day 30: Made my own game!\"", "The progress from start to finish was remarkable."],
            ["At the school talent show, {{CHILD}} presented their game.", "The screen was projected big so everyone could see.", "Classmates took turns playing and trying to beat each other's scores."],
            ["\"How long did it take to learn?\" the teacher asked.", "\"A lot of hours and a lot of persistence,\" {{CHILD}} answered.", "\"But every frustrating moment made the success sweeter.\""],
            ["{{MOTHER}} hugged {{CHILD}} after the talent show.", "\"You showed everyone what sticking with something looks like.\"", "{{CHILD}} felt like the bugs and frustrations had all been worth it."],
            ["At bedtime, the computer was closed but not forgotten.", "Tomorrow's challenge: adding sound effects to the game!", "{{CHILD}}'s mind was already planning the next feature."],
            ["\"What's your favorite thing about coding?\" {{MOTHER}} asked.", "{{CHILD}} thought for a moment. \"That bugs are just puzzles.\"", "\"And I really, really love puzzles.\""],
            ["The blue glow of the computer faded as it went to sleep mode.", "Both the computer and {{CHILD}} needed rest to be at their best.", "Even code needs time to compile — processors need breaks too."],
            ["Dreams came in blocks of color — drag, drop, connect.", "Dream-{{CHILD}} coded a world where everything was programmable.", "Clouds moved in loops, rainbows appeared on conditionals."],
            ["\"IF sun is shining, THEN show rainbow,\" dream-{{CHILD}} coded.", "And there it was — a perfect rainbow across the dream sky.", "In dreams, code became reality without any bugs at all."],
            ["The dream-game had infinite levels stretching to the horizon.", "Each level was a new kind of puzzle, never seen before.", "And dream-{{CHILD}} solved every one — persistent as always."],
            ["Morning would bring new challenges, new bugs, new victories.", "But tonight, the coder rested their thinking brain.", "Even Byte the robot was powered down, dreaming of zeros and ones."],
            ["The coding journal sat next to the pillow.", "Thirty days of persistence documented in excited handwriting.", "Every day a little better, a little more capable."],
            ["Outside, the stars flickered like pixels on a giant screen.", "The universe itself was the biggest program ever written.", "And {{CHILD}} was learning to speak its language."],
            ["Sleep was a system reboot — clearing the cache, refreshing memory.", "Tomorrow's {{CHILD}} would be faster, smarter, more persistent.", "Growth happens in rest as much as in effort."],
            ["The chair in front of the computer waited patiently.", "The screen would glow blue again in the morning.", "And a young coder would sit down and keep building."],
            ["Persistence isn't about never struggling.", "It's about struggling and choosing to continue anyway.", "{{CHILD}} had learned that, one bug at a time."],
            ["The house was quiet. The computer hummed softly.", "Inside its memory, {{CHILD}}'s game lived and waited.", "Ready for more stars, more levels, more improvements."],
            ["And deep in sleep, {{CHILD}}'s brain compiled the day's lessons.", "Loops, conditionals, functions, and most importantly: persistence.", "The code of a good life is written one determined line at a time."],
            ["Goodnight, little coder. Your program is running perfectly.", "Keep debugging, keep building, keep refusing to quit.", "Tomorrow's you will look back and be amazed at how far you've come."]
        ]
    },

];

module.exports = stories6to10;
